### ISSUE TITLE
1.6.3生成报错

### ISSUE THREAD

**Issue by AI1379** [fluid-dev/hexo-theme-fluid#130]
以前用的是1.5.0，没出过什么大的问题
之前换到1.6.3后使用`hexo g -d`时发生报错，信息如下(I:\blog是我博客的根目录)：
```text
ERROR Render HTML failed: google428b384b78bc6cce.html
TypeError: I:\blog\themes\fluid-1.6.1\layout\layout.ejs:10
    8| %>
    9|
 >> 10| <%- partial('_partial/head') %>
    11|
    12| <body>
    13|   <header style="height: <%- banner_img_height %>vh;">

I:\blog\themes\fluid-1.6.1\layout\_partial\head.ejs:21
    19|   <title><%= title %></title>
    20|
 >> 21|   <%- partial('_partial/css.ejs') %>
    22| </head>
    23|

I:\blog\themes\fluid-1.6.1\layout\_partial\css.ejs:12
    10| <%- css_ex(theme.static_prefix.internal_css, "main.css") %>
    11|
 >> 12| <% if (is_post && theme.post.image_zoom.enable) { %>
    13|   <%- css_ex(theme.static_prefix.fancybox, "jquery.fancybox.min.css") %>
    14| <% } %>
    15|

Cannot read property 'enable' of undefined
    at eval (I:\blog\themes\fluid-1.6.1\layout\_partial\css.ejs:38:45)
    at css (I:\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync.locals [as _compiledSync] (I:\blog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (I:\blog\node_modules\hexo\lib\theme\view.js:60:23)
    at Object.partial (I:\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (I:\blog\themes\fluid-1.6.1\layout\_partial\head.ejs:38:17)
    at head (I:\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync.locals [as _compiledSync] (I:\blog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (I:\blog\node_modules\hexo\lib\theme\view.js:60:23)
    at Object.partial (I:\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (I:\blog\themes\fluid-1.6.1\layout\layout.ejs:23:17)
    at layout (I:\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled.locals [as _compiled] (I:\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (I:\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at _compiled.then.result (I:\blog\node_modules\hexo\lib\theme\view.js:52:23)
    at tryCatcher (I:\blog\node_modules\bluebird\js\release\util.js:16:23)
```
换1.6.1了之后问题仍然没有解决，但重新换回1.5.0或1.5.1都没有问题
后来把`css.ejs`里报错的地方改成了`true`后仍然报错，但不是这个文件，信息也是`Cannot read property 'enable' of undefined`。
请问如何解决？

**Comment by zkqiang** [comment]
因为你更新后主题 _config.yml （或者覆盖配置的 fluid_config.yml）没有同步更新
报错的是你缺少新增的配置项
