### ISSUE TITLE
主题配置icons项为空导致main.css为空

### ISSUE THREAD

**Issue by Brzjomo** [fluid-dev/hexo-theme-fluid#154]
在主题配置文件的关于页设置中，字体图标icons项如果全部注释掉（如下图），刷新页面后会发现样式缺失，就是main.css为空。
![image](https://user-images.githubusercontent.com/28553949/75113931-0277bb00-568d-11ea-9f04-d90244c0e8fe.png)
页面：
![image](https://user-images.githubusercontent.com/28553949/75114079-ffc99580-568d-11ea-98fa-9bc2c9535110.png)

暂时的解决方法就是不要全部注释，至少剩一个（如下图）。
![image](https://user-images.githubusercontent.com/28553949/75113944-18857b80-568d-11ea-9b1d-294b7931435f.png)

**Comment by Brzjomo** [comment]
因为暂时解决，我关闭了。

**Comment by DogeLasVegas** [comment]
这应该是个bug吧，我也遇到了这个问题，只不过我的直接打不开了，而且会报错，报错的信息是这样的：
`
theme.about.icons is not iterable
    at eval (G:\temp\hexo-blog-source\themes\fluid\layout\about.ejs:25:38)
    at about (G:\temp\hexo-blog-source\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (G:\temp\hexo-blog-source\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (G:\temp\hexo-blog-source\node_modules\hexo\lib\theme\view.js:41:15)
    at G:\temp\hexo-blog-source\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (G:\temp\hexo-blog-source\node_modules\bluebird\js\release\util.js:16:23)
    at G:\temp\hexo-blog-source\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\temp\hexo-blog-source\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:468:10)
    at resume_ (_stream_readable.js:982:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Unhandled rejection TypeError: G:\temp\hexo-blog-source\themes\fluid\layout\about.ejs:15
    13|     <div class="about-intro"><%- theme.about.introduce %></div>
    14|     <div class="about-icons">
 >> 15|       <% for(const each of theme.about.icons) { %>
    16|         <% if (!each.class) continue; %>
    17|         <% var cls = each.class %>
    18|         <% var isQr = each.qrcode %>

theme.about.icons is not iterable
    at eval (G:\temp\hexo-blog-source\themes\fluid\layout\about.ejs:25:38)
    at about (G:\temp\hexo-blog-source\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (G:\temp\hexo-blog-source\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (G:\temp\hexo-blog-source\node_modules\hexo\lib\theme\view.js:41:15)
    at G:\temp\hexo-blog-source\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (G:\temp\hexo-blog-source\node_modules\bluebird\js\release\util.js:16:23)
    at G:\temp\hexo-blog-source\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\temp\hexo-blog-source\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:468:10)
    at resume_ (_stream_readable.js:982:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

`

**Comment by DogeLasVegas** [comment]
重新贴一下错误，另外我是在把下面icon都注释了之后重新刷新页面的时候就打不开，一直在加载，然后就有下面的错误信息，尝试clean并且重新generate，，但是在生成的时候也会报错，页面依旧打不开
```
theme.about.icons is not iterable
    at eval (G:\temp\hexo-blog-source\themes\fluid\layout\about.ejs:25:38)
    at about (G:\temp\hexo-blog-source\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (G:\temp\hexo-blog-source\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (G:\temp\hexo-blog-source\node_modules\hexo\lib\theme\view.js:41:15)
    at G:\temp\hexo-blog-source\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (G:\temp\hexo-blog-source\node_modules\bluebird\js\release\util.js:16:23)
    at G:\temp\hexo-blog-source\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\temp\hexo-blog-source\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:468:10)
    at resume_ (_stream_readable.js:982:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Unhandled rejection TypeError: G:\temp\hexo-blog-source\themes\fluid\layout\about.ejs:15
    13|     <div class="about-intro"><%- theme.about.introduce %></div>
    14|     <div class="about-icons">
 >> 15|       <% for(const each of theme.about.icons) { %>
    16|         <% if (!each.class) continue; %>
    17|         <% var cls = each.class %>
    18|         <% var isQr = each.qrcode %>

theme.about.icons is not iterable
    at eval (G:\temp\hexo-blog-source\themes\fluid\layout\about.ejs:25:38)
    at about (G:\temp\hexo-blog-source\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (G:\temp\hexo-blog-source\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (G:\temp\hexo-blog-source\node_modules\hexo\lib\theme\view.js:41:15)
    at G:\temp\hexo-blog-source\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (G:\temp\hexo-blog-source\node_modules\bluebird\js\release\util.js:16:23)
    at G:\temp\hexo-blog-source\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\temp\hexo-blog-source\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:468:10)
    at resume_ (_stream_readable.js:982:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```
