### ISSUE TITLE
tag插件的组图不能用吗？

### ISSUE THREAD

**Issue by yyccqqq** [fluid-dev/hexo-theme-fluid#229]
使用后报错，错误如下：
Template render error: (unknown path)
  TypeError: Cannot read property 'getHTML' of undefined
     at Object._prettifyError (D:\GitHub\Hexo\node_modules\nunjucks\src\lib.js:36:11)
     at D:\GitHub\Hexo\node_modules\nunjucks\src\environment.js:561:19
     at Template.root [as rootRenderFunc] (eval at _compile 
    (D:\GitHub\Hexo\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:32:3)
    at Template.render (D:\GitHub\Hexo\node_modules\nunjucks\src\environment.js:550:10)
    at Environment.renderString 
    (D:\GitHub\Hexo\node_modules\nunjucks\src\environment.js:378:17)
    at D:\GitHub\Hexo\node_modules\hexo\lib\extend\tag.js:120:48
    at tryCatcher (D:\GitHub\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback 
    (D:\GitHub\Hexo\node_modules\bluebird\js\release\promise.js:209:30)
    at Tag.render (D:\GitHub\Hexo\node_modules\hexo\lib\extend\tag.js:120:18)
    at Object.onRenderEnd (D:\GitHub\Hexo\node_modules\hexo\lib\hexo\post.js:291:22)
    at D:\GitHub\Hexo\node_modules\hexo\lib\hexo\render.js:79:21
    at tryCatcher (D:\GitHub\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler 
    (D:\GitHub\Hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\GitHub\Hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 
    (D:\GitHub\Hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\GitHub\Hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\GitHub\Hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\GitHub\Hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\GitHub\Hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues 
    (D:\GitHub\Hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
这个怎么解决？

**Comment by zkqiang** [comment]
请把你使用的代码贴出来，还有使用的主题版本

**Comment by yyccqqq** [comment]
内容：
{% gi 5 3-2 %}

  ![](1.jpg)

  ![](2.jpg)

  ![](3.jpg)

  ![](4.jpg)

  ![](5.jpg)

{% endgi %}
这图片路径瞎写的，实际图片路径是HTTPS链接
版本：1.8.0
开启的插件：音乐播放 、评论valine 、一言
配置方式：覆盖配置
tag插件的便签能够正常使用，请问一下，是不是需要配置什么？或者配置文件出错了？

**Comment by yyccqqq** [comment]
内容：
`{% gi 5 3-2 %}

  ![](1.jpg)

  ![](2.jpg)

  ![](3.jpg)

  ![](4.jpg)

  ![](5.jpg)

{% endgi %}`

这图片路径瞎写的，实际图片路径是HTTPS链接
版本：1.8.0
开启的插件：音乐播放 、评论valine 、一言
配置方式：覆盖配置
tag插件的便签能够正常使用，请问一下，是不是需要配置什么？或者配置文件出错了？

**Comment by yyccqqq** [comment]
内容：
`{% gi 5 3-2 %}`
`![](1.jpg)`
`![](1.jpg)`
`![](1.jpg)`
`![](1.jpg)`
`![](1.jpg)`
`{% endgi %}`
版本：1.8.0
额外开启的功能：评论valine 、音乐播放、一言
配置方式：覆盖配置
实际图片链接时https方式的链接
请问这是什么原因？

**Comment by zkqiang** [comment]
你应该不是  1.8.0 正式版吧，建议重新升级 release 试下，这个报错我记得 beta 期间修复了

**Comment by yyccqqq** [comment]
谢谢，是版本的问题。
