### ISSUE TITLE
本地调试出错

### ISSUE THREAD

**Issue by seineo** [fluid-dev/hexo-theme-fluid#271]
#### 请确认
- [Yes ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ Yes] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
在已经使用`hexo clean`的情况下，`hexo s`仍然报错，信息如下：
> Fatal Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: spawn /home/seineo/Desktop/CS/blog/node_modules/optipng-bin/vendor/optipng ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

本来是可以的，但在装了压缩插件`hexo-all-minifier`后便报错了，即使在配置文件删除`all_minifier: true`后也还是报错，不知道是不是受这个插件影响。

**Comment by seineo** [comment]
突然又找到了解决方法，使用`npm rebuild`即可。
详见：https://github.com/imagemin/optipng-bin/issues/84
