### ISSUE TITLE
在使用组图的报错

### ISSUE THREAD

**Issue by v-tawe** [fluid-dev/hexo-theme-fluid#324]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

在使用组图语法:

```
{% gi 5 3-2 %}
  ![](/images/banner/hello.png)
  ![](/images/banner/hello.png)
  ![](/images/banner/hello.png)
  ![](/images/banner/hello.png)
  ![](/images/banner/hello.png)
{% endgi %}
```

`hexo s` 就会报错：

```
FATAL {
  err: Template render error: (unknown path)
    unexpected end of file
      at Object._prettifyError (E:\Blog\node_modules\nunjucks\src\lib.js:36:11)
      at Template.render (E:\Blog\node_modules\nunjucks\src\environment.js:536:21)
      at Environment.renderString (E:\Blog\node_modules\nunjucks\src\environment.js:378:17)
      at E:\Blog\node_modules\hexo\lib\extend\tag.js:236:16
      at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Function.Promise.fromNode.Promise.fromCallback (E:\Blog\node_modules\bluebird\js\release\promise.js:209:30)
      at Tag.render (E:\Blog\node_modules\hexo\lib\extend\tag.js:235:20)
      at Object.onRenderEnd (E:\Blog\node_modules\hexo\lib\hexo\post.js:273:22)
      at E:\Blog\node_modules\hexo\lib\hexo\render.js:79:21
      at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    cause: Template render error: (unknown path)
      unexpected end of file
        at Object._prettifyError (E:\Blog\node_modules\nunjucks\src\lib.js:36:11)
        at Template.render (E:\Blog\node_modules\nunjucks\src\environment.js:536:21)
        at Environment.renderString (E:\Blog\node_modules\nunjucks\src\environment.js:378:17)
        at E:\Blog\node_modules\hexo\lib\extend\tag.js:236:16
        at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
        at Function.Promise.fromNode.Promise.fromCallback (E:\Blog\node_modules\bluebird\js\release\promise.js:209:30)
        at Tag.render (E:\Blog\node_modules\hexo\lib\extend\tag.js:235:20)
        at Object.onRenderEnd (E:\Blog\node_modules\hexo\lib\hexo\post.js:273:22)
        at E:\Blog\node_modules\hexo\lib\hexo\render.js:79:21
        at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
        at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
        at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
        at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
        at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
        at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
        at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
        at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
        at Immediate.Async.drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
        at processImmediate (internal/timers.js:456:21) {
      name: 'Template render error'
    },
    isOperational: true
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

**Comment by zkqiang** [comment]
语法没什么问题，怀疑可能是别的地方导致报错

**Comment by v-tawe** [comment]
强哥，找了半天没找到啥原因，不过只要我把这段注释掉就不报错了，不知道咋回事：
https://v-tawe.github.io/2020/07/others-fluid-guide/#%E7%BB%84%E5%9B%BE

**Comment by zkqiang** [comment]
看不出是什么问题，可以单独测试一下

**Comment by v-tawe** [comment]
好的 谢谢
