### ISSUE TITLE
Script load failed highlight.js

### ISSUE THREAD

**Issue by nanhaiyufu** [fluid-dev/hexo-theme-fluid#327]
```
 1 $ hexo g                                                                                                                                                                                           2 failed: themes/fluid/scripts/events/lib/highlight.js                                                                                                                                               3 themes/fluid/scripts/events/lib/highlight.js:22                                                                                                                                                    4 return html.replace(/(?<!<div class="hljs">)<pre.*?(class=".+?".*?)*>(.*?)<\/pre>/gis, (str, p1, p2) => {                                                                                          5 ^                                                                                                                                                                                                  6 SyntaxError: Invalid regular expression flags                                                                                                                                                      7 at createScript (vm.js:74:10)                                                                                                                                                                      8 at Object.runInThisContext (vm.js:116:10)  

```

**Comment by zkqiang** [comment]
对不起，发 issue 请提供足够的信息

highlight 相关的报错，请先检查自己的 package.json 有没有其他高亮插件
