### ISSUE TITLE
执行hexo g出现错误，导致全局丢失样式文件

### ISSUE THREAD

**Issue by mokeeqian** [fluid-dev/hexo-theme-fluid#732]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

在本地执行`hexo g`时出现：
```
ERROR {
  err: OperationalError: D:\BLOG\BLOG_BETA\node_modules\hexo-theme-fluid\source\css\main.styl:12:23
      8| @import "_functions/base"
      9|
     10| @import "_mixins/base"
     11|
     12| @import "_pages/pages"
  -----------------------------^
     13|

  failed to locate @import file D:\BLOG\BLOG_BETA\node_modules\stylus\lib\functions\index.styl

      at Evaluator.visitImport (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:915:21)
      at Evaluator.Visitor.visit (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\index.js:28:40)
      at Evaluator.visit (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:160:18)
      at Evaluator.visitRoot (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:707:27)
      at Evaluator.Visitor.visit (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\index.js:28:40)
      at Evaluator.visit (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:160:18)
      at Evaluator.evaluate (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:247:15)
      at Renderer.render (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\renderer.js:86:26)
      at Hexo.stylusFn (D:\BLOG\BLOG_BETA\node_modules\hexo-renderer-stylus\lib\renderer.js:59:6)
      at Hexo.tryCatcher (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.ret (eval at makeNodePromisifiedEval (C:\Users\mokeeqian\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
      at D:\BLOG\BLOG_BETA\node_modules\hexo\lib\hexo\render.js:81:22
      at tryCatcher (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:439:21) {
    cause: Error: D:\BLOG\BLOG_BETA\node_modules\hexo-theme-fluid\source\css\main.styl:12:23
        8| @import "_functions/base"
        9|
       10| @import "_mixins/base"
       11|
       12| @import "_pages/pages"
    -----------------------------^
       13|

    failed to locate @import file D:\BLOG\BLOG_BETA\node_modules\stylus\lib\functions\index.styl

        at Evaluator.visitImport (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:915:21)
        at Evaluator.Visitor.visit (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\index.js:28:40)
        at Evaluator.visit (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:160:18)
        at Evaluator.visitRoot (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:707:27)
        at Evaluator.Visitor.visit (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\index.js:28:40)
        at Evaluator.visit (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:160:18)
        at Evaluator.evaluate (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\visitor\evaluator.js:247:15)
        at Renderer.render (D:\BLOG\BLOG_BETA\node_modules\stylus\lib\renderer.js:86:26)
        at Hexo.stylusFn (D:\BLOG\BLOG_BETA\node_modules\hexo-renderer-stylus\lib\renderer.js:59:6)
        at Hexo.tryCatcher (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\util.js:16:23)
        at Hexo.ret (eval at makeNodePromisifiedEval (C:\Users\mokeeqian\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
        at D:\BLOG\BLOG_BETA\node_modules\hexo\lib\hexo\render.js:81:22
        at tryCatcher (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\util.js:16:23)
        at Promise._settlePromiseFromHandler (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\promise.js:547:31)
        at Promise._settlePromise (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\promise.js:604:18)
        at Promise._settlePromise0 (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\promise.js:649:10)
        at Promise._settlePromises (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\promise.js:729:18)
        at _drainQueueStep (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\async.js:93:12)
        at _drainQueue (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\async.js:86:9)
        at Async._drainQueues (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\async.js:102:5)
        at Immediate.Async.drainQueues [as _onImmediate] (D:\BLOG\BLOG_BETA\node_modules\bluebird\js\release\async.js:15:14)
        at processImmediate (internal/timers.js:439:21) {
      lineno: 12,
      column: 23,
      filename: 'D:\\BLOG\\BLOG_BETA\\node_modules\\hexo-theme-fluid\\source\\css\\main.styl',
      stylusStack: '',
      input: '// --------------------------------------\n' +
        '// Fluid\n' +
        '// https://github.com/fluid-dev/hexo-theme-fluid\n' +
        '// --------------------------------------\n' +
        '\n' +
        '@import "_variables/base"\n' +
        '\n' +
        '@import "_functions/base"\n' +
        '\n' +
        '@import "_mixins/base"\n' +
        '\n' +
        '@import "_pages/pages"\n'
    },
    isOperational: true,
    lineno: 12,
    column: 23,
    filename: 'D:\\BLOG\\BLOG_BETA\\node_modules\\hexo-theme-fluid\\source\\css\\main.styl',
    stylusStack: '',
    input: '// --------------------------------------\n' +
      '// Fluid\n' +
      '// https://github.com/fluid-dev/hexo-theme-fluid\n' +
      '// --------------------------------------\n' +
      '\n' +
      '@import "_variables/base"\n' +
      '\n' +
      '@import "_functions/base"\n' +
      '\n' +
      '@import "_mixins/base"\n' +
      '\n' +
      '@import "_pages/pages"\n'
  }
} Asset render failed: %s css/main.css

```

**Comment by zkqiang** [comment]
请检查自己 hexo 依赖是否完整，然后尝试删除 `node_modules` 重新 npm install

**Comment by mokeeqian** [comment]
> 

感谢，暂时已经解决问题了
