### ISSUE TITLE
使用 Fluid 代码注入功能插入 ejs 时无法使用 hexo.extend.filter.register 注册的函数

### ISSUE THREAD

**Issue by MangK** [fluid-dev/hexo-theme-fluid#841]
#### 请确认
- [-] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [-] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

使用 Fluid 代码注入功能插入 ejs 时，在 ejs 文件内无法使用 hexo.extend.filter.register 注册的函数

ReferenceError: Dir/source/js/tags.ejs:1
 >> 1| <% myFunc() %>

myFunc is not defined
    at eval ("Dir/source/js/myejs.ejs":10:8)
    at tags (Dir/node_modules/ejs/lib/ejs.js:703:17)
    at exports.render (Dir/node_modules/ejs/lib/ejs.js:425:37)
    at Hexo.ejsRenderer (Dir/node_modules/hexo-renderer-ejs/lib/renderer.js:6:14)
    at Hexo.tryCatcher (Dir/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (Dir/node_modules/bluebird/js/release/method.js:15:34)
    at Dir/node_modules/hexo/lib/hexo/render.js:81:22
    at tryCatcher (Dir/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (Dir/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (Dir/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (Dir/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (Dir/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (Dir/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (Dir/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (Dir/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)

**Comment by zkqiang** [comment]
尝试 register 第二个参数传 `-999` 试试？（只是猜测，我没有试过）

**Comment by MangK** [comment]
抱歉前面描述错误。
现实情况是无法在ejs文件中使用 hexo.extend.helper.register 注册的函数

**Comment by zkqiang** [comment]
> 抱歉前面描述错误。 现实情况是无法在ejs文件中使用 hexo.extend.helper.register 注册的函数

ejs 本身就不能使用，因为 ejs 是渲染模板，而 hexo.extend 是 nodejs 后端，可以直接写在 blog/scripts 目录下，类似于 https://hexo.fluid-dev.com/posts/hexo-injector/
