### ISSUE TITLE
执行生成命令时报错

### ISSUE THREAD

**Issue by Lixuannan** [fluid-dev/hexo-theme-fluid#847]
在执行`hexo g`的时候报错如下
```
INFO  Validating config
INFO  Start processing
INFO  
------------------------------------------------
|                                              |
|     ________  __            _        __      |
|    |_   __  |[  |          (_)      |  ]     |
|      | |_ \_| | | __   _   __   .--.| |      |
|      |  _|    | |[  | | | [  |/ /'`\' |      |
|     _| |_     | | | \_/ |, | || \__/  |      |
|    |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                              |
|             感谢使用 Fluid 主题 !            |
|    文档: https://hexo.fluid-dev.com/docs/    |
|                                              |
------------------------------------------------

INFO  Files loaded in 504 ms
ERROR Error: /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:82
    80|             </div>
    81| 
 >> 82|             <%- inject_point('postComments') %>
    83|           </article>
    84|         </div>
    85|       </div>

/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:3
    1| <% if ((!is_post() && !is_page()) || (is_post() && theme.post.comments.enable && page.comments) || (is_page() && page.comments)) { %>
    2|   <article id="comments">
 >> 3|     <%- partial('_partials/comments/' + (typeof page.comment === 'string' && page.comment !== '' ? page.comment : theme.post.comments.type)) %>
    4|   </article>
    5| <% } %>
    6| 

Partial _partials/comments/null does not exist. (in inject/postComments/default.ejs)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:16:11)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:13:17)
    at default (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:23
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:6)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:156:17)
    at post (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  path: '/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs'
}
ERROR Error: /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:82
    80|             </div>
    81| 
 >> 82|             <%- inject_point('postComments') %>
    83|           </article>
    84|         </div>
    85|       </div>

/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:3
    1| <% if ((!is_post() && !is_page()) || (is_post() && theme.post.comments.enable && page.comments) || (is_page() && page.comments)) { %>
    2|   <article id="comments">
 >> 3|     <%- partial('_partials/comments/' + (typeof page.comment === 'string' && page.comment !== '' ? page.comment : theme.post.comments.type)) %>
    4|   </article>
    5| <% } %>
    6| 

Partial _partials/comments/null does not exist. (in inject/postComments/default.ejs)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:16:11)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:13:17)
    at default (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:23
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:6)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:156:17)
    at post (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  path: '/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs'
}
ERROR Error: /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:82
    80|             </div>
    81| 
 >> 82|             <%- inject_point('postComments') %>
    83|           </article>
    84|         </div>
    85|       </div>

/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:3
    1| <% if ((!is_post() && !is_page()) || (is_post() && theme.post.comments.enable && page.comments) || (is_page() && page.comments)) { %>
    2|   <article id="comments">
 >> 3|     <%- partial('_partials/comments/' + (typeof page.comment === 'string' && page.comment !== '' ? page.comment : theme.post.comments.type)) %>
    4|   </article>
    5| <% } %>
    6| 

Partial _partials/comments/null does not exist. (in inject/postComments/default.ejs)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:16:11)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:13:17)
    at default (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:23
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:6)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:156:17)
    at post (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  path: '/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs'
}
ERROR Error: /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:82
    80|             </div>
    81| 
 >> 82|             <%- inject_point('postComments') %>
    83|           </article>
    84|         </div>
    85|       </div>

/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:3
    1| <% if ((!is_post() && !is_page()) || (is_post() && theme.post.comments.enable && page.comments) || (is_page() && page.comments)) { %>
    2|   <article id="comments">
 >> 3|     <%- partial('_partials/comments/' + (typeof page.comment === 'string' && page.comment !== '' ? page.comment : theme.post.comments.type)) %>
    4|   </article>
    5| <% } %>
    6| 

Partial _partials/comments/null does not exist. (in inject/postComments/default.ejs)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:16:11)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:13:17)
    at default (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:23
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:6)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:156:17)
    at post (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  path: '/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs'
}
ERROR Error: /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:82
    80|             </div>
    81| 
 >> 82|             <%- inject_point('postComments') %>
    83|           </article>
    84|         </div>
    85|       </div>

/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:3
    1| <% if ((!is_post() && !is_page()) || (is_post() && theme.post.comments.enable && page.comments) || (is_page() && page.comments)) { %>
    2|   <article id="comments">
 >> 3|     <%- partial('_partials/comments/' + (typeof page.comment === 'string' && page.comment !== '' ? page.comment : theme.post.comments.type)) %>
    4|   </article>
    5| <% } %>
    6| 

Partial _partials/comments/null does not exist. (in inject/postComments/default.ejs)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:16:11)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/inject/postComments/default.ejs:13:17)
    at default (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:23
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:6)
    at eval (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs:156:17)
    at post (/Users/meizhenchen/Desktop/Project/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/meizhenchen/Desktop/Project/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  path: '/Users/meizhenchen/Desktop/Project/blog/node_modules/hexo-theme-fluid/layout/post.ejs'
}
INFO  Generated: js/duration.js
INFO  Generated: post/hello-world.html
INFO  Generated: local-search.xml
INFO  Generated: archives/index.html
INFO  Generated: archives/2022/index.html
INFO  Generated: archives/2022/08/index.html
INFO  Generated: archives/2022/10/index.html
INFO  Generated: post/Oiclass.com Q&A P1106.html
INFO  Generated: post/OiClass.com Q&A P1194.html
INFO  Generated: post/OiClass.com Q&A P1626.html
INFO  Generated: about/index.html
INFO  Generated: post/OiClass.com Q&A P2569.html
INFO  Generated: img/avatar.png
INFO  Generated: xml/local-search.xml
INFO  Generated: index.html
INFO  Generated: img/fluid.png
INFO  Generated: 404.html
INFO  Generated: images/favicon.png
INFO  Generated: images/icon.png
INFO  Generated: css/highlight-dark.css
INFO  Generated: img/police_beian.png
INFO  Generated: img/loading.gif
INFO  Generated: css/highlight.css
INFO  Generated: tags/题解/index.html
INFO  Generated: css/gitalk.css
INFO  Generated: js/events.js
INFO  Generated: js/color-schema.js
INFO  Generated: js/img-lazyload.js
INFO  Generated: js/boot.js
INFO  Generated: js/leancloud.js
INFO  Generated: js/plugins.js
INFO  Generated: js/utils.js
INFO  Generated: css/main.css
INFO  Generated: tags/分享/index.html
INFO  Generated: js/local-search.js
INFO  Generated: tags/问答/index.html
INFO  Generated: tags/Oiclass-com/index.html
INFO  Generated: images/banner.jpeg
INFO  Generated: img/default.png
INFO  39 files generated in 571 ms
```

**Comment by Lixuannan** [comment]
项目采用最新版hexo-cli和最新版fluid主题

**Comment by zkqiang** [comment]
配置项 `comments` 用默认值试试

**Comment by Lixuannan** [comment]
Thank you
