### ISSUE TITLE
我的部署炸了

### ISSUE THREAD

**Issue by Sinetian** [fluid-dev/hexo-theme-fluid#921]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)

#### Describe the question
[ 12:04下午 ]  [ root@192:~/Documents/blogsite ]
 $ hexo clean && hexo deploy
INFO  Validating config
INFO  Deleted database.
INFO  Deleted public folder.
INFO  Validating config
INFO  Start processing
INFO  
------------------------------------------------
|                                              |
|     ________  __            _        __      |
|    |_   __  |[  |          (_)      |  ]     |
|      | |_ \_| | | __   _   __   .--.| |      |
|      |  _|    | |[  | | | [  |/ /'`\' |      |
|     _| |_     | | | \_/ |, | || \__/  |      |
|    |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                              |
|             感谢使用 Fluid 主题 !            |
|    文档: https://hexo.fluid-dev.com/docs/    |
|                                              |
------------------------------------------------

INFO  Files loaded in 130 ms
ERROR 
Error: /Users/tomly/Documents/blogsite/node_modules/hexo-theme-fluid/layout/links.ejs:40
    38| <% } %>
    39| 
 >> 40| <%- inject_point('linksComments') %>
    41| 

/Users/tomly/Documents/blogsite/node_modules/hexo-theme-fluid/layout/inject/linksComments/default.ejs:5
    3|   <% if (commentType) { %>
    4|     <article id="comments">
 >> 5|       <%- partial('_partials/comments/' + commentType) %>
    6|     </article>
    7|   <% } %>
    8| <% } %>

Partial _partials/comments/gisqus does not exist. (in inject/linksComments/default.ejs)
    at Object.partial (/Users/tomly/Documents/blogsite/node_modules/hexo/lib/plugins/helper/partial.js:16:11)
    at eval ("/Users/tomly/Documents/blogsite/node_modules/hexo-theme-fluid/layout/inject/linksComments/default.ejs":19:17)
    at default (/Users/tomly/Documents/blogsite/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/Users/tomly/Documents/blogsite/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/tomly/Documents/blogsite/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/Users/tomly/Documents/blogsite/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at /Users/tomly/Documents/blogsite/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:23
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/tomly/Documents/blogsite/node_modules/hexo-theme-fluid/scripts/helpers/engine.js:7:6)
    at eval ("/Users/tomly/Documents/blogsite/node_modules/hexo-theme-fluid/layout/links.ejs":63:17)
    at links (/Users/tomly/Documents/blogsite/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/Users/tomly/Documents/blogsite/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/tomly/Documents/blogsite/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/tomly/Documents/blogsite/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/tomly/Documents/blogsite/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/tomly/Documents/blogsite/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/tomly/Documents/blogsite/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
INFO  Generated: local-search.xml
INFO  Generated: tags/index.html
INFO  Generated: archives/2023/03/index.html
INFO  Generated: archives/index.html
INFO  Generated: about/index.html
INFO  Generated: archives/2023/index.html
INFO  Generated: links/index.html
INFO  Generated: 404.html
INFO  Generated: img/avatar.png
INFO  Generated: index.html
INFO  Generated: categories/index.html
INFO  Generated: img/fluid.png
INFO  Generated: img/loading.gif
INFO  Generated: img/police_beian.png
INFO  Generated: xml/local-search.xml
INFO  Generated: js/boot.js
INFO  Generated: css/gitalk.css
INFO  Generated: css/highlight.css
INFO  Generated: js/img-lazyload.js
INFO  Generated: js/color-schema.js
INFO  Generated: js/events.js
INFO  Generated: js/utils.js
INFO  Generated: css/highlight-dark.css
INFO  Generated: js/local-search.js
INFO  Generated: js/plugins.js
INFO  Generated: js/leancloud.js
INFO  Generated: css/main.css
INFO  Generated: 2023/03/11/hello-world/index.html
INFO  Generated: img/default.png
INFO  29 files generated in 179 ms
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
[main 26ce9ff] Site updated: 2023-03-12 12:06:16
 1 file changed, 3 insertions(+), 3 deletions(-)
Enumerating objects: 100, done.
Counting objects: 100% (100/100), done.
Delta compression using up to 8 threads
Compressing objects: 100% (70/70), done.
Writing objects: 100% (100/100), 464.60 KiB | 20.20 MiB/s, done.
Total 100 (delta 32), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (32/32), done.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: Cannot force-push to this branch
To https://github.com/Sinetian/sinetian.github.io
 ! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Sinetian/sinetian.github.io'
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Spawn failed
    at ChildProcess.<anonymous> (/Users/tomly/Documents/blogsite/node_modules/hexo-util/lib/spawn.js:51:21)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
日志就这个

**Comment by zkqiang** [comment]
看不出问题，请检查文件和配置
