### ISSUE TITLE
更新后无法启动

### ISSUE THREAD

**Issue by nghuyong** [fluid-dev/hexo-theme-fluid#930]
更新插件到最新版：`npm update --save hexo-theme-fluid`

启动`hexo serve` 遇到报错

```
INFO  Validating config
ERROR {
  err: TypeError: fn must be a function
      at Helper.register (/Users/huyong/code/nghuyong/blog/node_modules/hexo/lib/extend/helper.js:31:41)
      at /Users/huyong/code/nghuyong/blog/node_modules/hexo-theme-fluid/scripts/helpers/utils.js:29:20
      at /Users/huyong/code/nghuyong/blog/node_modules/hexo/lib/hexo/index.js:305:14
      at tryCatcher (/Users/huyong/code/nghuyong/blog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/huyong/code/nghuyong/blog/node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (/Users/huyong/code/nghuyong/blog/node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (/Users/huyong/code/nghuyong/blog/node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (/Users/huyong/code/nghuyong/blog/node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (/Users/huyong/code/nghuyong/blog/node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (/Users/huyong/code/nghuyong/blog/node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/huyong/code/nghuyong/blog/node_modules/bluebird/js/release/async.js:17:14)
      at processImmediate (internal/timers.js:464:21)
} Script load failed: %s node_modules/hexo-theme-fluid/scripts/helpers/utils.js
INFO  Start processing
INFO  
```

**Comment by zkqiang** [comment]
把 hexo 也更新下试试
