### ISSUE TITLE
ERROR Script load failed: themes\fluid\scripts\events\lib\highlight.js

### ISSUE THREAD

**Issue by kittsai** [fluid-dev/hexo-theme-fluid#952]
INFO  Validating config
ERROR Script load failed: themes\fluid\scripts\events\lib\highlight.js
Error: Cannot find module 'css'
Require stack:
- E:\KitBlog\themes\fluid\scripts\events\lib\highlight.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at req (E:\KitBlog\node_modules\hexo\lib\hexo\index.js:292:23)
    at E:\KitBlog\themes\fluid\scripts\events\lib\highlight.js:4:13
    at E:\KitBlog\node_modules\hexo\lib\hexo\index.js:305:14
    at tryCatcher (E:\KitBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\KitBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\KitBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\KitBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\KitBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\KitBlog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\KitBlog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\KitBlog\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (E:\KitBlog\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)

**Comment by iSonce** [comment]
same problem

**Comment by mjc-alex** [comment]
try:
``` bash
npm install css --save
```

**Comment by iSonce** [comment]
Dependabot removes css and creates a pr to my blog project.

**Comment by sofiworker** [comment]
same problem, but https://github.com/fluid-dev/hexo-theme-fluid/issues/952#issuecomment-1562767661 help

**Comment by kittsai** [comment]
> try:
> 
> ```shell
> npm install css --save
> ```

thanks!

**Comment by zkqiang** [comment]
Fixed in [v1.9.5](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.5)

**Comment by rogerlp** [comment]
> try: 尝试：
> 
> ```shell
> npm install css --save
> ```

it works, thank you.
