### ISSUE TITLE
生成文件时的报错

### ISSUE THREAD

**Issue by TTT-TD** [fluid-dev/hexo-theme-fluid#976]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

> 您好开发者，我遇到了和 #916 一样的问题，看到回复是环境问题，并不清楚具体在哪一块出现问题，一下是我执行`hexo g`时的错误部分输出

```
INFO  Validating config
INFO  Start processing
INFO  
------------------------------------------------
|                                              |
|     ________  __            _        __      |
|    |_   __  |[  |          (_)      |  ]     |
|      | |_ \_| | | __   _   __   .--.| |      |
|      |  _|    | |[  | | | [  |/ /'`\' |      |
|     _| |_     | | | \_/ |, | || \__/  |      |
|    |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                              |
|             感谢使用 Fluid 主题 !            |
|    文档: https://hexo.fluid-dev.com/docs/    |
|                                              |
------------------------------------------------

INFO  Files loaded in 1.16 s
ERROR 
TypeError: /opt/hexo/node_modules/hexo-theme-fluid/layout/category.ejs:12
    10| %>
    11| 
 >> 12| <%- partial('_partials/archive-list.ejs', { params: { key: page.layout, postTotal: cat ? cat.posts.length : 0 } }) %>
    13| 

/opt/hexo/node_modules/hexo-theme-fluid/layout/_partials/archive-list.ejs:5
    3|   <hr>
    4|   <% var dateCursor %>
 >> 5|   <% page.posts.each(function (post) { %>
    6|     <% if(date(post.date, "YYYY") !== dateCursor) { %>
    7|       <% dateCursor = date(post.date, "YYYY") %>
    8|       <p class="h5"><%= dateCursor %></p>

Cannot read properties of undefined (reading 'each')
    at eval ("/opt/hexo/node_modules/hexo-theme-fluid/layout/_partials/archive-list.ejs":18:19)
    at archive-list (/opt/hexo/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/opt/hexo/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/opt/hexo/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/opt/hexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval ("/opt/hexo/node_modules/hexo-theme-fluid/layout/category.ejs":23:17)
    at category (/opt/hexo/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/opt/hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/opt/hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /opt/hexo/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/opt/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/opt/hexo/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR 
TypeError: /opt/hexo/node_modules/hexo-theme-fluid/layout/tag.ejs:12
    10| %>
    11| 
 >> 12| <%- partial('_partials/archive-list.ejs', { params: { key: page.layout, postTotal: tag ? tag.posts.length : 0 } }) %>
    13| 

/opt/hexo/node_modules/hexo-theme-fluid/layout/_partials/archive-list.ejs:5
    3|   <hr>
    4|   <% var dateCursor %>
 >> 5|   <% page.posts.each(function (post) { %>
    6|     <% if(date(post.date, "YYYY") !== dateCursor) { %>
    7|       <% dateCursor = date(post.date, "YYYY") %>
    8|       <p class="h5"><%= dateCursor %></p>

Cannot read properties of undefined (reading 'each')
    at eval ("/opt/hexo/node_modules/hexo-theme-fluid/layout/_partials/archive-list.ejs":18:19)
    at archive-list (/opt/hexo/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/opt/hexo/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/opt/hexo/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/opt/hexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval ("/opt/hexo/node_modules/hexo-theme-fluid/layout/tag.ejs":23:17)
    at tag (/opt/hexo/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/opt/hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/opt/hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /opt/hexo/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/opt/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/opt/hexo/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**当前环境信息**：
- Hexo 6.3.0
- NPM 9.8.0
- nodejs v18.13.0

**当前已安装的插件情况**:
```
hexo-site@0.0.0 /opt/hexo
├── hexo-deployer-git@4.0.0
├── hexo-external-link@1.0.9
├── hexo-feed@1.1.1
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-sitemap@3.0.1
├── hexo-generator-tag@2.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@6.0.0
├── hexo-renderer-stylus@2.1.0
├── hexo-seo-autopush@2.0.3
├── hexo-server@3.0.0
├── hexo-theme-fluid@1.9.5-a
├── hexo-theme-landscape@0.0.3
├── hexo-uuid@1.0.2
├── hexo@6.3.0
├── moment@2.29.4
└── node-libcurl@3.0.0
```

**Comment by TTT-TD** [comment]
已经解决了，文章内容中我原本分类和标签字段用的是tag和category，换成标准复数形式就行了，tags categories
